# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9dfef6be018ea3e49639e517ae1a068bebeffea89c5debe5c954d7c901b0e1b80022eb4884ca22e12ed94831d9f51c6172f37d455ed7e2672a4d3c26e489ffb

test:
  secret_key_base: 556443c0ae0e385b675d55c6a358feee37f03b3af7fb6315cf2e477889e9d237483400d9e2a4e326d8a478c112bd3cc36d5e5274d3db8fb4d77d2dd455e90411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
